### ISSUE TITLE
Why oh why.

### ISSUE THREAD

**Issue by 31415pi** [nextthingco/CHIP-linux#1]
Came here to get some dip for the CHIPs I found in my misc. microcontroller bin. Want to use them for HUD units, since they have some potent tech for the smol form factor. Anyone know where all these files have gone. rip *tear*

hellomoto1123 at gmai l dot com.

**Comment by blinkengus** [comment]
Hi, you can find mirrors at https://github.com/chip-community/chip-linux
and https://archive.org/details/NextThingCo.GitArchive

**Comment by 31415pi** [comment]
Thanks m8
