### ISSUE TITLE
Enable CONFIG_PPP to make ChipPhone

### ISSUE THREAD

**Issue by aerialist** [NextThingCo/CHIP-linux#58]
Need PPP support to use cellular modems. 
May need a few more CONFIG_PPP_\* 's.

https://wiki.archlinux.org/index.php/pppd
ftp://ftp.lyx.org/pub/sgml-tools/website/HOWTO/PPP-HOWTO/t1345.html
https://archlinuxarm.org/forum/viewtopic.php?f=29&t=2972
http://www.stlinux.com/howto/network/PPP

**Comment by zerotri** [comment]
Thanks for the note. We did add some PPP options here:
dc9c0d3d8f382966ba4142d65dda7bb0d022b120

This matches with the stlinux link. We also enabled quite a few USB serial devices here which should help the situation. I'll look into adding the others as well.
84fd65dc12d9d0ece485adf8ac01cd3f354fb7d9

**Comment by computermouth** [comment]
Done!
