### ISSUE TITLE
Add support for OpenGL ES 2.0

### ISSUE THREAD

**Issue by JamesHagerman** [NextThingCo/CHIP-linux#62]
Hey all,

A few months back, I remember someone was working on getting OpenGL ES support into the kernel for the CHIP.

Any updates on this? What's the main blocker?

**Comment by computermouth** [comment]
Just announced!

https://bbs.nextthing.co/t/c-h-i-p-pocketc-h-i-p-in-stock-for-the-holidays-3d-acceleration-alpha/11108

**Comment by JamesHagerman** [comment]
OMG THANK YOU!!!

Wow! I don't know how to day that any more clearly!
