### ISSUE TITLE
Please add vpu support

### ISSUE THREAD

**Issue by gschmall** [NextThingCo/CHIP-linux#63]
Please add vpu support.

https://github.com/FlorentRevest/linux-sunxi-cedrus
https://github.com/FlorentRevest/sunxi-cedrus-drv-video

or use in house drivers if they are superior to the FR drivers.

thanks.

**Comment by mripard** [comment]
Hi,

Unfortunately, this is nothing but a prototype at the moment, and it's definitely not ready for prime time. And an even more unfortunate thing is that we don't have an alternative yet...

**Comment by gschmall** [comment]
Since the state of things are not ready for vpu prime time, Ill close this issue for now.
